using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace CourseRegisterApplication.Server.Migrations
{
    /// <inheritdoc />
    public partial class Initial : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Departments",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    DepartmentSpecificId = table.Column<string>(type: "nvarchar(450)", nullable: true),
                    DepartmentName = table.Column<string>(type: "nvarchar(450)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Departments", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "PriorityTypes",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    PriorityName = table.Column<string>(type: "nvarchar(450)", nullable: true),
                    TuitionDiscountRate = table.Column<float>(type: "real", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PriorityTypes", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Provinces",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    ProvinceName = table.Column<string>(type: "nvarchar(450)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Provinces", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Roles",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    RoleName = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Roles", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Branches",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    BranchSpecificId = table.Column<string>(type: "nvarchar(450)", nullable: true),
                    BranchName = table.Column<string>(type: "nvarchar(450)", nullable: true),
                    DepartmentId = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Branches", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Branches_Departments_DepartmentId",
                        column: x => x.DepartmentId,
                        principalTable: "Departments",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "Districts",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    DistrictName = table.Column<string>(type: "nvarchar(450)", nullable: true),
                    IsPriority = table.Column<bool>(type: "bit", nullable: false),
                    ProvinceId = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Districts", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Districts_Provinces_ProvinceId",
                        column: x => x.ProvinceId,
                        principalTable: "Provinces",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "Users",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Username = table.Column<string>(type: "nvarchar(450)", nullable: true),
                    Password = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Email = table.Column<string>(type: "nvarchar(450)", nullable: true),
                    RoleId = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Users", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Users_Roles_RoleId",
                        column: x => x.RoleId,
                        principalTable: "Roles",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "Students",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    StudentSpecificId = table.Column<string>(type: "nvarchar(450)", nullable: true),
                    FullName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DateOfBirth = table.Column<DateTime>(type: "datetime2", nullable: false),
                    Gender = table.Column<int>(type: "int", nullable: false),
                    DistrictId = table.Column<int>(type: "int", nullable: false),
                    BranchId = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Students", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Students_Branches_BranchId",
                        column: x => x.BranchId,
                        principalTable: "Branches",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Students_Districts_DistrictId",
                        column: x => x.DistrictId,
                        principalTable: "Districts",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "StudentPriorityTypes",
                columns: table => new
                {
                    StudentId = table.Column<int>(type: "int", nullable: false),
                    PriorityTypeId = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_StudentPriorityTypes", x => new { x.StudentId, x.PriorityTypeId });
                    table.ForeignKey(
                        name: "FK_StudentPriorityTypes_PriorityTypes_PriorityTypeId",
                        column: x => x.PriorityTypeId,
                        principalTable: "PriorityTypes",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_StudentPriorityTypes_Students_StudentId",
                        column: x => x.StudentId,
                        principalTable: "Students",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Departments",
                columns: new[] { "Id", "DepartmentName", "DepartmentSpecificId" },
                values: new object[,]
                {
                    { 1, "Khoa Học Máy Tính", "KHMT" },
                    { 2, "Công Nghệ Phần Mềm", "CNPM" },
                    { 3, "Kỹ Thuật Máy Tính", "KTMT" },
                    { 4, "Hệ Thống Thông Tin", "HTTT" },
                    { 5, "Mạng máy tính và Truyền thông", "MMT&TT" },
                    { 6, "Khoa Học và Kỹ thuật thông tin", "KH&KTTT" }
                });

            migrationBuilder.InsertData(
                table: "PriorityTypes",
                columns: new[] { "Id", "PriorityName", "TuitionDiscountRate" },
                values: new object[,]
                {
                    { 1, "Không thuộc đối tượng ưu tiên", 0f },
                    { 2, "Vùng sâu vùng xa", 0.3f },
                    { 3, "Con thương binh", 0.5f },
                    { 4, "Con liệt sĩ", 0.8f }
                });

            migrationBuilder.InsertData(
                table: "Provinces",
                columns: new[] { "Id", "ProvinceName" },
                values: new object[,]
                {
                    { 1, "Thành phố Hà Nội" },
                    { 2, "Tỉnh Hà Giang" },
                    { 3, "Tỉnh Cao Bằng" },
                    { 4, "Tỉnh Bắc Kạn" },
                    { 5, "Tỉnh Tuyên Quang" },
                    { 6, "Tỉnh Lào Cai" },
                    { 7, "Tỉnh Điện Biên" },
                    { 8, "Tỉnh Lai Châu" },
                    { 9, "Tỉnh Sơn La" },
                    { 10, "Tỉnh Yên Bái" },
                    { 11, "Tỉnh Hòa Bình" },
                    { 12, "Tỉnh Thái Nguyên" },
                    { 13, "Tỉnh Lạng Sơn" },
                    { 14, "Tỉnh Quảng Ninh" },
                    { 15, "Tỉnh Bắc Giang" },
                    { 16, "Tỉnh Phú Thọ" },
                    { 17, "Tỉnh Vĩnh Phúc" },
                    { 18, "Tỉnh Bắc Ninh" },
                    { 19, "Tỉnh Hải Dương" },
                    { 20, "Thành phố Hải Phòng" },
                    { 21, "Tỉnh Hưng Yên" },
                    { 22, "Tỉnh Thái Bình" },
                    { 23, "Tỉnh Hà Nam" },
                    { 24, "Tỉnh Nam Định" },
                    { 25, "Tỉnh Ninh Bình" },
                    { 26, "Tỉnh Thanh Hóa" },
                    { 27, "Tỉnh Nghệ An" },
                    { 28, "Tỉnh Hà Tĩnh" },
                    { 29, "Tỉnh Quảng Bình" },
                    { 30, "Tỉnh Quảng Trị" },
                    { 31, "Tỉnh Thừa Thiên Huế" },
                    { 32, "Thành phố Đà Nẵng" },
                    { 33, "Tỉnh Quảng Nam" },
                    { 34, "Tỉnh Quảng Ngãi" },
                    { 35, "Tỉnh Bình Định" },
                    { 36, "Tỉnh Phú Yên" },
                    { 37, "Tỉnh Khánh Hòa" },
                    { 38, "Tỉnh Ninh THuyện" },
                    { 39, "Tỉnh Bình THuyện" },
                    { 40, "Tỉnh Kon Tum" },
                    { 41, "Tỉnh Gia Lai" },
                    { 42, "Tỉnh Đắk Lắk" },
                    { 43, "Tỉnh Đăk Nông" },
                    { 44, "Tỉnh Lâm Đồng" },
                    { 45, "Tỉnh Bình Phước" },
                    { 46, "Tỉnh Tây Ninh" },
                    { 47, "Tỉnh Bình Dương" },
                    { 48, "Tỉnh Đồng Nai" },
                    { 49, "Tỉnh Bà Rịa - Vũng Tàu" },
                    { 50, "Thành phố Hồ Chí Minh" },
                    { 51, "Tỉnh Long An" },
                    { 52, "Tỉnh Tiền Giang" },
                    { 53, "Tỉnh Bến Tre" },
                    { 54, "Tỉnh Trà Vinh" },
                    { 55, "Tỉnh Vĩnh Long" },
                    { 56, "Tỉnh Đồng Tháp" },
                    { 57, "Tỉnh An Giang" },
                    { 58, "Tỉnh Kiên Giang" },
                    { 59, "Thành phố Cần Thơ" },
                    { 60, "Tỉnh Hậu Giang" },
                    { 61, "Tỉnh Sóc Trăng" },
                    { 62, "Tỉnh Bạc Liêu" },
                    { 63, "Tỉnh Cà Mau;" }
                });

            migrationBuilder.InsertData(
                table: "Roles",
                columns: new[] { "Id", "RoleName" },
                values: new object[,]
                {
                    { 1, 0 },
                    { 2, 1 },
                    { 3, 2 }
                });

            migrationBuilder.InsertData(
                table: "Branches",
                columns: new[] { "Id", "BranchName", "BranchSpecificId", "DepartmentId" },
                values: new object[,]
                {
                    { 1, "Khoa học máy tính", "KHMT", 1 },
                    { 2, "Trí tuệ nhân tạo", "TTNT", 1 },
                    { 3, "Kĩ thuật phần mềm", "KTPM", 2 },
                    { 4, "Kỹ thuật máy tính", "KTMT", 3 },
                    { 5, "Hệ thống thông tin", "HTTT", 4 },
                    { 6, "Thương mại điện tử", "TMDT", 4 },
                    { 7, "Mạng máy tính", "MMT", 5 },
                    { 8, "An toàn thông tin", "ATTT", 5 },
                    { 9, "Công nghệ thông tin", "CNTT", 6 },
                    { 10, "Khoa học dữ liệu", "KHDL", 6 }
                });

            migrationBuilder.InsertData(
                table: "Districts",
                columns: new[] { "Id", "DistrictName", "IsPriority", "ProvinceId" },
                values: new object[,]
                {
                    { 1, "Huyện Ba Đình", false, 1 },
                    { 2, "Huyện Hoàn Kiếm", false, 1 },
                    { 3, "Huyện Tây Hồ", false, 1 },
                    { 4, "Huyện Long Biên", false, 1 },
                    { 5, "Huyện Cầu Giấy", false, 1 },
                    { 6, "Huyện Đống Đa", false, 1 },
                    { 7, "Huyện Hai Bà Trưng", false, 1 },
                    { 8, "Huyện Hoàng Mai", false, 1 },
                    { 9, "Huyện Thanh Xuân", false, 1 },
                    { 10, "Huyện Sóc Sơn", false, 1 },
                    { 11, "Huyện Đông Anh", false, 1 },
                    { 12, "Huyện Gia Lâm", false, 1 },
                    { 13, "Huyện Nam Từ Liêm", false, 1 },
                    { 14, "Huyện Thanh Trì", false, 1 },
                    { 15, "Huyện Bắc Từ Liêm", false, 1 },
                    { 16, "Huyện Mê Linh", false, 1 },
                    { 17, "Huyện Hà Đông", false, 1 },
                    { 18, "Thị xã Sơn Tây", false, 1 },
                    { 19, "Huyện Ba Vì", true, 1 },
                    { 20, "Huyện Phúc Thọ", false, 1 },
                    { 21, "Huyện Đan Phượng", false, 1 },
                    { 22, "Huyện Hoài Đức", false, 1 },
                    { 23, "Huyện Quốc Oai", false, 1 },
                    { 24, "Huyện Thạch Thất", false, 1 },
                    { 25, "Huyện Chương Mỹ", false, 1 },
                    { 26, "Huyện Thanh Oai", false, 1 },
                    { 27, "Huyện Thường Tín", false, 1 },
                    { 28, "Huyện Phú Xuyên", false, 1 },
                    { 29, "Huyện Ứng Hòa", false, 1 },
                    { 30, "Huyện Mỹ Đức", false, 1 },
                    { 31, "Thành phố Hà Giang", true, 2 },
                    { 32, "Huyện Đồng Văn", true, 2 },
                    { 33, "Huyện Mèo Vạc", true, 2 },
                    { 34, "Huyện Yên Minh", true, 2 },
                    { 35, "Huyện Quản Bạ", true, 2 },
                    { 36, "Huyện Vị Xuyên", true, 2 },
                    { 37, "Huyện Bắc Mê", true, 2 },
                    { 38, "Huyện Hoàng Su Phì", true, 2 },
                    { 39, "Huyện Xín Mần", true, 2 },
                    { 40, "Huyện Bắc Quang", true, 2 },
                    { 41, "Huyện Quang Bình", true, 2 },
                    { 42, "Thành phố Cao Bằng", true, 3 },
                    { 43, "Huyện Bảo Lâm", true, 3 },
                    { 44, "Huyện Bảo Lạc", true, 3 },
                    { 45, "Huyện Hà Quảng", true, 3 },
                    { 46, "Huyện Trùng Khánh", true, 3 },
                    { 47, "Huyện Hạ Lang", true, 3 },
                    { 48, "Huyện Quảng Hòa", true, 3 },
                    { 49, "Huyện Hoà An", true, 3 },
                    { 50, "Huyện Nguyên Bình", true, 3 },
                    { 51, "Huyện Thạch An", true, 3 },
                    { 52, "Thành Phố Bắc Kạn", true, 4 },
                    { 53, "Huyện Pác Nặm", true, 4 },
                    { 54, "Huyện Ba Bể", true, 4 },
                    { 55, "Huyện Ngân Sơn", true, 4 },
                    { 56, "Huyện Bạch Thông", true, 4 },
                    { 57, "Huyện Chợ Đồn", true, 4 },
                    { 58, "Huyện Chợ Mới", true, 4 },
                    { 59, "Huyện Na Rì", true, 4 },
                    { 60, "Thành phố Tuyên Quang", true, 5 },
                    { 61, "Huyện Lâm Bình", true, 5 },
                    { 62, "Huyện Na Hang", true, 5 },
                    { 63, "Huyện Chiêm Hóa", true, 5 },
                    { 64, "Huyện Hàm Yên", true, 5 },
                    { 65, "Huyện Yên Sơn", true, 5 },
                    { 66, "Huyện Sơn Dương", true, 5 },
                    { 67, "Thành phố Lào Cai", true, 6 },
                    { 68, "Huyện Bát Xát", true, 6 },
                    { 69, "Huyện Mường Khương", true, 6 },
                    { 70, "Huyện Si Ma Cai", true, 6 },
                    { 71, "Huyện Bắc Hà", true, 6 },
                    { 72, "Huyện Bảo Thắng", true, 6 },
                    { 73, "Huyện Bảo Yên", true, 6 },
                    { 74, "Thị xã Sa Pa", true, 6 },
                    { 75, "Huyện Văn Bàn", true, 6 },
                    { 76, "Thành phố Điện Biên Phủ", true, 7 },
                    { 77, "Thị Xã Mường Lay", true, 7 },
                    { 78, "Huyện Mường Nhé", true, 7 },
                    { 79, "Huyện Mường Chà", true, 7 },
                    { 80, "Huyện Tủa Chùa", true, 7 },
                    { 81, "Huyện Tuần Giáo", true, 7 },
                    { 82, "Huyện Điện Biên", true, 7 },
                    { 83, "Huyện Điện Biên Đông", true, 7 },
                    { 84, "Huyện Mường Ảng", true, 7 },
                    { 85, "Huyện Nậm Pồ", true, 7 },
                    { 86, "Thành phố Lai Châu", true, 8 },
                    { 87, "Huyện Tam Đường", true, 8 },
                    { 88, "Huyện Mường Tè", true, 8 },
                    { 89, "Huyện Sìn Hồ", true, 8 },
                    { 90, "Huyện Phong Thổ", true, 8 },
                    { 91, "Huyện Than Uyên", true, 8 },
                    { 92, "Huyện Tân Uyên", true, 8 },
                    { 93, "Huyện Nậm Nhùn", true, 8 },
                    { 94, "Thành phố Sơn La", true, 9 },
                    { 95, "Huyện Quỳnh Nhai", true, 9 },
                    { 96, "Huyện THuyện Châu", true, 9 },
                    { 97, "Huyện Mường La", true, 9 },
                    { 98, "Huyện Bắc Yên", true, 9 },
                    { 99, "Huyện Phù Yên", true, 9 },
                    { 100, "Huyện Mộc Châu", true, 9 },
                    { 101, "Huyện Yên Châu", true, 9 },
                    { 102, "Huyện Mai Sơn", true, 9 },
                    { 103, "Huyện Sông Mã", true, 9 },
                    { 104, "Huyện Sốp Cộp", true, 9 },
                    { 105, "Huyện Vân Hồ", true, 9 },
                    { 106, "Thành phố Yên Bái", true, 10 },
                    { 107, "Thị xã Nghĩa Lộ", true, 10 },
                    { 108, "Huyện Lục Yên", true, 10 },
                    { 109, "Huyện Văn Yên", true, 10 },
                    { 110, "Huyện Mù Căng Chải", true, 10 },
                    { 111, "Huyện Trấn Yên", true, 10 },
                    { 112, "Huyện Trạm Tấu", true, 10 },
                    { 113, "Huyện Văn Chấn", true, 10 },
                    { 114, "Huyện Yên Bình", true, 10 },
                    { 115, "Thành phố Hòa Bình", true, 11 },
                    { 116, "Huyện Đà Bắc", true, 11 },
                    { 117, "Huyện Lương Sơn", true, 11 },
                    { 118, "Huyện Kim Bôi", true, 11 },
                    { 119, "Huyện Cao Phong", true, 11 },
                    { 120, "Huyện Tân Lạc", true, 11 },
                    { 121, "Huyện Mai Châu", true, 11 },
                    { 122, "Huyện Lạc Sơn", true, 11 },
                    { 123, "Huyện Yên Thủy", true, 11 },
                    { 124, "Huyện Lạc Thủy", true, 11 },
                    { 125, "Thành phố Thái Nguyên", true, 12 },
                    { 126, "Thành phố Sông Công", false, 12 },
                    { 127, "Huyện Định Hóa", true, 12 },
                    { 128, "Huyện Phú Lương", true, 12 },
                    { 129, "Huyện Đồng Hỷ", true, 12 },
                    { 130, "Huyện Võ Nhai", true, 12 },
                    { 131, "Huyện Đại Từ", true, 12 },
                    { 132, "Thị xã Phổ Yên", true, 12 },
                    { 133, "Huyện Phú Bình", true, 12 },
                    { 134, "Thành phố Lạng Sơn", true, 13 },
                    { 135, "Huyện Tràng Định", true, 13 },
                    { 136, "Huyện Bình Gia", true, 13 },
                    { 137, "Huyện Văn Lãng", true, 13 },
                    { 138, "Huyện Cao Lộc", true, 13 },
                    { 139, "Huyện Văn Quan", true, 13 },
                    { 140, "Huyện Bắc Sơn", true, 13 },
                    { 141, "Huyện Hữu Lũng", true, 13 },
                    { 142, "Huyện Chi Lăng", true, 13 },
                    { 143, "Huyện Lộc Bình", true, 13 },
                    { 144, "Huyện Đình Lập", true, 13 },
                    { 145, "Thành phố Hạ Long", false, 14 },
                    { 146, "Thành phố Móng Cái", false, 14 },
                    { 147, "Thành phố Cẩm Phả", false, 14 },
                    { 148, "Thành phố Uông Bí", false, 14 },
                    { 149, "Huyện Bình Liêu", true, 14 },
                    { 150, "Huyện Tiên Yên", true, 14 },
                    { 151, "Huyện Đầm Hà", true, 14 },
                    { 152, "Huyện Hải Hà", true, 14 },
                    { 153, "Huyện Ba Chẽ", true, 14 },
                    { 154, "Huyện Vân Đồn", true, 14 },
                    { 155, "Thị xã Đông Triều", true, 14 },
                    { 156, "Thị xã Quảng Yên", false, 14 },
                    { 157, "Huyện Cô Tô", true, 14 },
                    { 158, "Thành phố Bắc Giang", false, 15 },
                    { 159, "Huyện Yên Thế", false, 15 },
                    { 160, "Huyện Tân Yên", false, 15 },
                    { 161, "Huyện Lạng Giang", true, 15 },
                    { 162, "Huyện Lục Nam", false, 15 },
                    { 163, "Huyện Lục Ngạn", false, 15 },
                    { 164, "Huyện Sơn Động", false, 15 },
                    { 165, "Huyện Yên Dũng", false, 15 },
                    { 166, "Huyện Việt Yên", true, 15 },
                    { 167, "Huyện Hiệp Hòa", true, 15 },
                    { 168, "Thành phố Việt Trì", false, 16 },
                    { 169, "Thị xã Phú Thọ", false, 16 },
                    { 170, "Huyện Đoan Hùng", true, 16 },
                    { 171, "Huyện Hạ Hoà", true, 16 },
                    { 172, "Huyện Thanh Ba", true, 16 },
                    { 173, "Huyện Phù Ninh", true, 16 },
                    { 174, "Huyện Yên Lập", true, 16 },
                    { 175, "Huyện Cẩm Khê", true, 16 },
                    { 176, "Huyện Tam Nông", true, 16 },
                    { 177, "Huyện Lâm Thao", true, 16 },
                    { 178, "Huyện Thanh Sơn", true, 16 },
                    { 179, "Huyện Thanh Thuỷ", true, 16 },
                    { 180, "Huyện Tân Sơn", true, 16 },
                    { 181, "Thành phố Vĩnh Yên", false, 17 },
                    { 182, "Thành phố Phúc Yên", false, 17 },
                    { 183, "Huyện Lập Thạch", false, 17 },
                    { 184, "Huyện Tam Dương", false, 17 },
                    { 185, "Huyện Tam Đảo", true, 17 },
                    { 186, "Huyện Bình Xuyên", true, 17 },
                    { 187, "Huyện Yên Lạc", false, 17 },
                    { 188, "Huyện Vĩnh Tường", false, 17 },
                    { 189, "Huyện Sông Lô", false, 17 },
                    { 190, "Thành phố Bắc Ninh", false, 18 },
                    { 191, "Huyện Yên Phong", false, 18 },
                    { 192, "Huyện Quế Võ", false, 18 },
                    { 193, "Huyện Tiên Du", false, 18 },
                    { 194, "Thành phố Từ Sơn", false, 18 },
                    { 195, "Huyện THuyện Thành", false, 18 },
                    { 196, "Huyện Gia Bình", false, 18 },
                    { 197, "Huyện Lương Tài", false, 18 },
                    { 198, "Thành phố Hải Dương", false, 19 },
                    { 199, "Thành phố Chí Linh", true, 19 },
                    { 200, "Huyện Nam Sách", false, 19 },
                    { 201, "Thị xã Kinh Môn", true, 19 },
                    { 202, "Huyện Kim Thành", false, 19 },
                    { 203, "Huyện Thanh Hà", false, 19 },
                    { 204, "Huyện Cẩm Giàng", false, 19 },
                    { 205, "Huyện Bình Giang", false, 19 },
                    { 206, "Huyện Gia Lộc", false, 19 },
                    { 207, "Huyện Tứ Kỳ", false, 19 },
                    { 208, "Huyện Ninh Giang", false, 19 },
                    { 209, "Huyện Thanh Miện", false, 19 },
                    { 210, "Huyện Hồng Bàng", false, 20 },
                    { 211, "Huyện Ngô Quyền", false, 20 },
                    { 212, "Huyện Lê Chân", false, 20 },
                    { 213, "Huyện Hải An", false, 20 },
                    { 214, "Huyện Kiến An", false, 20 },
                    { 215, "Huyện Đồ Sơn", false, 20 },
                    { 216, "Huyện Dương Kinh", false, 20 },
                    { 217, "Huyện Thuỷ Nguyên", true, 20 },
                    { 218, "Huyện An Dương", false, 20 },
                    { 219, "Huyện An Lão", false, 20 },
                    { 220, "Huyện Kiến Thuỵ", false, 20 },
                    { 221, "Huyện Tiên Lãng", false, 20 },
                    { 222, "Huyện Vĩnh Bảo", false, 20 },
                    { 223, "Huyện Cát Hải", true, 20 },
                    { 224, "Huyện Bạch Long Vĩ", false, 20 },
                    { 225, "Thành phố Hưng Yên", false, 21 },
                    { 226, "Huyện Văn Lâm", false, 21 },
                    { 227, "Huyện Văn Giang", false, 21 },
                    { 228, "Huyện Yên Mỹ", false, 21 },
                    { 229, "Thị xã Mỹ Hào", false, 21 },
                    { 230, "Huyện Ân Thi", false, 21 },
                    { 231, "Huyện Khoái Châu", false, 21 },
                    { 232, "Huyện Kim Động", false, 21 },
                    { 233, "Huyện Tiên Lữ", false, 21 },
                    { 234, "Huyện Phù Cừ", false, 21 },
                    { 235, "Thành phố Thái Bình", false, 22 },
                    { 236, "Huyện Quỳnh Phụ", false, 22 },
                    { 237, "Huyện Hưng Hà", false, 22 },
                    { 238, "Huyện Đông Hưng", false, 22 },
                    { 239, "Huyện Thái Thụy", false, 22 },
                    { 240, "Huyện Tiền Hải", false, 22 },
                    { 241, "Huyện Kiến Xương", false, 22 },
                    { 242, "Huyện Vũ Thư", false, 22 },
                    { 243, "Thành phố Phủ Lý", false, 23 },
                    { 244, "Thị xã Duy Tiên", false, 23 },
                    { 245, "Huyện Kim Bảng", false, 23 },
                    { 246, "Huyện Thanh Liêm", false, 23 },
                    { 247, "Huyện Bình Lục", false, 23 },
                    { 248, "Huyện Lý Nhân", false, 23 },
                    { 249, "Thành phố Nam Định", false, 24 },
                    { 250, "Huyện Mỹ Lộc", false, 24 },
                    { 251, "Huyện Vụ Bản", false, 24 },
                    { 252, "Huyện Ý Yên", false, 24 },
                    { 253, "Huyện Nghĩa Hưng", false, 24 },
                    { 254, "Huyện Nam Trực", false, 24 },
                    { 255, "Huyện Trực Ninh", false, 24 },
                    { 256, "Huyện Xuân Trường", false, 24 },
                    { 257, "Huyện Giao Thủy", false, 24 },
                    { 258, "Huyện Hải Hậu", false, 24 },
                    { 259, "Thành phố Ninh Bình", false, 25 },
                    { 260, "Thành phố Tam Điệp", true, 25 },
                    { 261, "Huyện Nho Quan", true, 25 },
                    { 262, "Huyện Gia Viễn", true, 25 },
                    { 263, "Huyện Hoa Lư", true, 25 },
                    { 264, "Huyện Yên Khánh", false, 25 },
                    { 265, "Huyện Kim Sơn", true, 25 },
                    { 266, "Huyện Yên Mô", true, 25 },
                    { 267, "Thành phố Thanh Hóa", false, 26 },
                    { 268, "Thị xã Bỉm Sơn", false, 26 },
                    { 269, "Thành phố Sầm Sơn", false, 26 },
                    { 270, "Huyện Mường Lát", true, 26 },
                    { 271, "Huyện Quan Hóa", true, 26 },
                    { 272, "Huyện Bá Thước", true, 26 },
                    { 273, "Huyện Quan Sơn", true, 26 },
                    { 274, "Huyện Lang Chánh", true, 26 },
                    { 275, "Huyện Ngọc Lặc", true, 26 },
                    { 276, "Huyện Cẩm Thủy", true, 26 },
                    { 277, "Huyện Thạch Thành", true, 26 },
                    { 278, "Huyện Hà Trung", false, 26 },
                    { 279, "Huyện Vĩnh Lộc", false, 26 },
                    { 280, "Huyện Yên Định", false, 26 },
                    { 281, "Huyện Thọ Xuân", false, 26 },
                    { 282, "Huyện Thường Xuân", true, 26 },
                    { 283, "Huyện Triệu Sơn", false, 26 },
                    { 284, "Huyện Thiệu Hóa", false, 26 },
                    { 285, "Huyện Hoằng Hóa", false, 26 },
                    { 286, "Huyện Hậu Lộc", false, 26 },
                    { 287, "Huyện Nga Sơn", false, 26 },
                    { 288, "Huyện Như Xuân", true, 26 },
                    { 289, "Huyện Như Thanh", true, 26 },
                    { 290, "Huyện Nông Cống", false, 26 },
                    { 291, "Huyện Đông Sơn", false, 26 },
                    { 292, "Huyện Quảng Xương", false, 26 },
                    { 293, "Thị xã Nghi Sơn", true, 26 },
                    { 294, "Thành phố Vinh", false, 27 },
                    { 295, "Thị xã Cửa Lò", false, 27 },
                    { 296, "Thị xã Thái Hoà", false, 27 },
                    { 297, "Huyện Quế Phong", true, 27 },
                    { 298, "Huyện Quỳ Châu", true, 27 },
                    { 299, "Huyện Kỳ Sơn", true, 27 },
                    { 300, "Huyện Tương Dương", true, 27 },
                    { 301, "Huyện Nghĩa Đàn", true, 27 },
                    { 302, "Huyện Quỳ Hợp", true, 27 },
                    { 303, "Huyện Quỳnh Lưu", false, 27 },
                    { 304, "Huyện Con Cuông", true, 27 },
                    { 305, "Huyện Tân Kỳ", true, 27 },
                    { 306, "Huyện Anh Sơn", true, 27 },
                    { 307, "Huyện Diễn Châu", false, 27 },
                    { 308, "Huyện Yên Thành", false, 27 },
                    { 309, "Huyện Đô Lương", false, 27 },
                    { 310, "Huyện Thanh Chương", false, 27 },
                    { 311, "Huyện Nghi Lộc", false, 27 },
                    { 312, "Huyện Nam Đàn", false, 27 },
                    { 313, "Huyện Hưng Nguyên", false, 27 },
                    { 314, "Thị xã Hoàng Mai", false, 27 },
                    { 315, "Thành phố Hà Tĩnh", false, 28 },
                    { 316, "Thị xã Hồng Lĩnh", false, 28 },
                    { 317, "Huyện Hương Sơn", false, 28 },
                    { 318, "Huyện Đức Thọ", true, 28 },
                    { 319, "Huyện Vũ Quang", false, 28 },
                    { 320, "Huyện Nghi Xuân", false, 28 },
                    { 321, "Huyện Can Lộc", true, 28 },
                    { 322, "Huyện Hương Khê", false, 28 },
                    { 323, "Huyện Thạch Hà", true, 28 },
                    { 324, "Huyện Cẩm Xuyên", true, 28 },
                    { 325, "Huyện Kỳ Anh", true, 28 },
                    { 326, "Huyện Lộc Hà", true, 28 },
                    { 327, "Thị xã Kỳ Anh", true, 28 },
                    { 328, "Thành Phố Đồng Hới", false, 29 },
                    { 329, "Huyện Minh Hóa", false, 29 },
                    { 330, "Huyện Tuyên Hóa", false, 29 },
                    { 331, "Huyện Quảng Trạch", true, 29 },
                    { 332, "Huyện Bố Trạch", true, 29 },
                    { 333, "Huyện Quảng Ninh", true, 29 },
                    { 334, "Huyện Lệ Thủy", true, 29 },
                    { 335, "Thị xã Ba Đồn", true, 29 },
                    { 336, "Thành phố Đông Hà", false, 30 },
                    { 337, "Thị xã Quảng Trị", false, 30 },
                    { 338, "Huyện Vĩnh Linh", true, 30 },
                    { 339, "Huyện Hướng Hóa", false, 30 },
                    { 340, "Huyện Gio Linh", true, 30 },
                    { 341, "Huyện Đa Krông", false, 30 },
                    { 342, "Huyện Cam Lộ", true, 30 },
                    { 343, "Huyện Triệu Phong", true, 30 },
                    { 344, "Huyện Hải Lăng", true, 30 },
                    { 345, "Huyện Cồn Cỏ", false, 30 },
                    { 346, "Thành phố Huế", false, 31 },
                    { 347, "Huyện Phong Điền", true, 31 },
                    { 348, "Huyện Quảng Điền", true, 31 },
                    { 349, "Huyện Phú Vang", true, 31 },
                    { 350, "Thị xã Hương Thủy", false, 31 },
                    { 351, "Thị xã Hương Trà", true, 31 },
                    { 352, "Huyện A Lưới", false, 31 },
                    { 353, "Huyện Phú Lộc", true, 31 },
                    { 354, "Huyện Nam Đông", false, 31 },
                    { 355, "Huyện Liên Chiểu", false, 32 },
                    { 356, "Huyện Thanh Khê", false, 32 },
                    { 357, "Huyện Hải Châu", false, 32 },
                    { 358, "Huyện Sơn Trà", false, 32 },
                    { 359, "Huyện Ngũ Hành Sơn", false, 32 },
                    { 360, "Huyện Cẩm Lệ", false, 32 },
                    { 361, "Huyện Hòa Vang", false, 32 },
                    { 362, "Huyện Hoàng Sa", true, 32 },
                    { 363, "Thành phố Tam Kỳ", false, 33 },
                    { 364, "Thành phố Hội An", false, 33 },
                    { 365, "Huyện Tây Giang", false, 33 },
                    { 366, "Huyện Đông Giang", false, 33 },
                    { 367, "Huyện Đại Lộc", true, 33 },
                    { 368, "Thị xã Điện Bàn", false, 33 },
                    { 369, "Huyện Duy Xuyên", true, 33 },
                    { 370, "Huyện Quế Sơn", false, 33 },
                    { 371, "Huyện Nam Giang", false, 33 },
                    { 372, "Huyện Phước Sơn", false, 33 },
                    { 373, "Huyện Hiệp Đức", false, 33 },
                    { 374, "Huyện Thăng Bình", true, 33 },
                    { 375, "Huyện Tiên Phước", false, 33 },
                    { 376, "Huyện Bắc Trà My", false, 33 },
                    { 377, "Huyện Nam Trà My", false, 33 },
                    { 378, "Huyện Núi Thành", true, 33 },
                    { 379, "Huyện Phú Ninh", true, 33 },
                    { 380, "Huyện Nông Sơn", false, 33 },
                    { 381, "Thành phố Quảng Ngãi", false, 34 },
                    { 382, "Huyện Bình Sơn", false, 34 },
                    { 383, "Huyện Trà Bồng", true, 34 },
                    { 384, "Huyện Sơn Tịnh", false, 34 },
                    { 385, "Huyện Tư Nghĩa", false, 34 },
                    { 386, "Huyện Sơn Hà", true, 34 },
                    { 387, "Huyện Sơn Tây", true, 34 },
                    { 388, "Huyện Minh Long", true, 34 },
                    { 389, "Huyện Nghĩa Hành", false, 34 },
                    { 390, "Huyện Mộ Đức", false, 34 },
                    { 391, "Thị xã Đức Phổ", true, 34 },
                    { 392, "Huyện Ba Tơ", true, 34 },
                    { 393, "Huyện Lý Sơn", true, 34 },
                    { 394, "Thành phố Quy Nhơn", false, 35 },
                    { 395, "Huyện An Lão", true, 35 },
                    { 396, "Thị xã Hoài Nhơn", false, 35 },
                    { 397, "Huyện Hoài Ân", false, 35 },
                    { 398, "Huyện Phù Mỹ", false, 35 },
                    { 399, "Huyện Vĩnh Thạnh", true, 35 },
                    { 400, "Huyện Tây Sơn", false, 35 },
                    { 401, "Huyện Phù Cát", false, 35 },
                    { 402, "Thị xã An Nhơn", false, 35 },
                    { 403, "Huyện Tuy Phước", true, 35 },
                    { 404, "Huyện Vân Canh", true, 35 },
                    { 405, "Thành phố Tuy Hoà", false, 36 },
                    { 406, "Thị xã Sông Cầu", true, 36 },
                    { 407, "Huyện Đồng Xuân", false, 36 },
                    { 408, "Huyện Tuy An", true, 36 },
                    { 409, "Huyện Sơn Hòa", false, 36 },
                    { 410, "Huyện Sông Hinh", false, 36 },
                    { 411, "Huyện Tây Hòa", true, 36 },
                    { 412, "Huyện Phú Hoà", false, 36 },
                    { 413, "Thị xã Đông Hòa", false, 36 },
                    { 414, "Thành phố Nha Trang", false, 37 },
                    { 415, "Thành phố Cam Ranh", false, 37 },
                    { 416, "Huyện Cam Lâm", false, 37 },
                    { 417, "Huyện Vạn Ninh", true, 37 },
                    { 418, "Thị xã Ninh Hòa", false, 37 },
                    { 419, "Huyện Khánh Vĩnh", true, 37 },
                    { 420, "Huyện Diên Khánh", false, 37 },
                    { 421, "Huyện Khánh Sơn", true, 37 },
                    { 422, "Huyện Trường Sa", true, 37 },
                    { 423, "Thành phố Phan Rang-Tháp Chàm", false, 38 },
                    { 424, "Huyện Bác Ái", true, 38 },
                    { 425, "Huyện Ninh Sơn", true, 38 },
                    { 426, "Huyện Ninh Hải", false, 38 },
                    { 427, "Huyện Ninh Phước", true, 38 },
                    { 428, "Huyện THuyện Bắc", true, 38 },
                    { 429, "Huyện THuyện Nam", true, 38 },
                    { 430, "Thành phố Phan Thiết", false, 39 },
                    { 431, "Thị xã La Gi", false, 39 },
                    { 432, "Huyện Tuy Phong", true, 39 },
                    { 433, "Huyện Bắc Bình", true, 39 },
                    { 434, "Huyện Hàm THuyện Bắc", true, 39 },
                    { 435, "Huyện Hàm THuyện Nam", true, 39 },
                    { 436, "Huyện Tánh Linh", true, 39 },
                    { 437, "Huyện Đức Linh", true, 39 },
                    { 438, "Huyện Hàm Tân", true, 39 },
                    { 439, "Huyện Phú Quí", false, 39 },
                    { 440, "Thành phố Kon Tum", true, 40 },
                    { 441, "Huyện Đắk Glei", true, 40 },
                    { 442, "Huyện Ngọc Hồi", true, 40 },
                    { 443, "Huyện Đắk Tô", true, 40 },
                    { 444, "Huyện Kon Plông", true, 40 },
                    { 445, "Huyện Kon Rẫy", true, 40 },
                    { 446, "Huyện Đắk Hà", true, 40 },
                    { 447, "Huyện Sa Thầy", true, 40 },
                    { 448, "Huyện Tu Mơ Rông", true, 40 },
                    { 449, "Huyện Ia HDrai", true, 40 },
                    { 450, "Thành phố Pleiku", true, 41 },
                    { 451, "Thị xã An Khê", true, 41 },
                    { 452, "Thị xã Ayun Pa", true, 41 },
                    { 453, "Huyện KBang", true, 41 },
                    { 454, "Huyện Đăk Đoa", true, 41 },
                    { 455, "Huyện Chư Păh", true, 41 },
                    { 456, "Huyện Ia Grai", true, 41 },
                    { 457, "Huyện Mang Yang", true, 41 },
                    { 458, "Huyện Kông Chro", true, 41 },
                    { 459, "Huyện Đức Cơ", true, 41 },
                    { 460, "Huyện Chư Prông", true, 41 },
                    { 461, "Huyện Chư Sê", true, 41 },
                    { 462, "Huyện Đăk Pơ", true, 41 },
                    { 463, "Huyện Ia Pa", true, 41 },
                    { 464, "Huyện Krông Pa", true, 41 },
                    { 465, "Huyện Phú Thiện", true, 41 },
                    { 466, "Huyện Chư Pưh", true, 41 },
                    { 467, "Thành phố Buôn Ma Thuột", true, 42 },
                    { 468, "Thị Xã Buôn Hồ", true, 42 },
                    { 469, "Huyện Ea Hleo", true, 42 },
                    { 470, "Huyện Ea Súp", true, 42 },
                    { 471, "Huyện Buôn Đôn", true, 42 },
                    { 472, "Huyện Cư Mgar", true, 42 },
                    { 473, "Huyện Krông Búk", true, 42 },
                    { 474, "Huyện Krông Năng", true, 42 },
                    { 475, "Huyện Ea Kar", true, 42 },
                    { 476, "Huyện MĐrắk", true, 42 },
                    { 477, "Huyện Krông Bông", true, 42 },
                    { 478, "Huyện Krông Pắc", true, 42 },
                    { 479, "Huyện Krông A Na", true, 42 },
                    { 480, "Huyện Lắk", true, 42 },
                    { 481, "Huyện Cư Kuin", true, 42 },
                    { 482, "Thành phố Gia Nghĩa", true, 43 },
                    { 483, "Huyện Đăk Glong", true, 43 },
                    { 484, "Huyện Cư Jút", true, 43 },
                    { 485, "Huyện Đắk Mil", true, 43 },
                    { 486, "Huyện Krông Nô", true, 43 },
                    { 487, "Huyện Đắk Song", true, 43 },
                    { 488, "Huyện Đắk RLấp", true, 43 },
                    { 489, "Huyện Tuy Đức", true, 43 },
                    { 490, "Thành phố Đà Lạt", false, 44 },
                    { 491, "Thành phố Bảo Lộc", false, 44 },
                    { 492, "Huyện Đam Rông", true, 44 },
                    { 493, "Huyện Lạc Dương", true, 44 },
                    { 494, "Huyện Lâm Hà", true, 44 },
                    { 495, "Huyện Đơn Dương", true, 44 },
                    { 496, "Huyện Đức Trọng", true, 44 },
                    { 497, "Huyện Di Linh", true, 44 },
                    { 498, "Huyện Bảo Lâm", true, 44 },
                    { 499, "Huyện Đạ Huoai", true, 44 },
                    { 500, "Huyện Đạ Tẻh", true, 44 },
                    { 501, "Huyện Cát Tiên", true, 44 },
                    { 502, "Thị xã Phước Long", true, 45 },
                    { 503, "Thành phố Đồng Xoài", true, 45 },
                    { 504, "Thị xã Bình Long", true, 45 },
                    { 505, "Huyện Bù Gia Mập", true, 45 },
                    { 506, "Huyện Lộc Ninh", true, 45 },
                    { 507, "Huyện Bù Đốp", true, 45 },
                    { 508, "Huyện Hớn Quản", true, 45 },
                    { 509, "Huyện Đồng Phú", true, 45 },
                    { 510, "Huyện Bù Đăng", true, 45 },
                    { 511, "Huyện Chơn Thành", true, 45 },
                    { 512, "Huyện Phú Riềng", true, 45 },
                    { 513, "Thành phố Tây Ninh", false, 46 },
                    { 514, "Huyện Tân Biên", false, 46 },
                    { 515, "Huyện Tân Châu", true, 46 },
                    { 516, "Huyện Dương Minh Châu", false, 46 },
                    { 517, "Huyện Châu Thành", true, 46 },
                    { 518, "Thị xã Hòa Thành", false, 46 },
                    { 519, "Huyện Gò Dầu", false, 46 },
                    { 520, "Huyện Bến Cầu", true, 46 },
                    { 521, "Thị xã Trảng Bàng", false, 46 },
                    { 522, "Thành phố Thủ Dầu Một", false, 47 },
                    { 523, "Huyện Bàu Bàng", false, 47 },
                    { 524, "Huyện Dầu Tiếng", false, 47 },
                    { 525, "Thị xã Bến Cát", false, 47 },
                    { 526, "Huyện Phú Giáo", false, 47 },
                    { 527, "Thị xã Tân Uyên", false, 47 },
                    { 528, "Thành phố Dĩ An", false, 47 },
                    { 529, "Thành phố THuyện An", false, 47 },
                    { 530, "Huyện Bắc Tân Uyên", false, 47 },
                    { 531, "Thành phố Biên Hòa", false, 48 },
                    { 532, "Thành phố Long Khánh", false, 48 },
                    { 533, "Huyện Tân Phú", true, 48 },
                    { 534, "Huyện Vĩnh Cửu", false, 48 },
                    { 535, "Huyện Định Quán", true, 48 },
                    { 536, "Huyện Trảng Bom", false, 48 },
                    { 537, "Huyện Thống Nhất", false, 48 },
                    { 538, "Huyện Cẩm Mỹ", true, 48 },
                    { 539, "Huyện Long Thành", false, 48 },
                    { 540, "Huyện Xuân Lộc", true, 48 },
                    { 541, "Huyện Nhơn Trạch", false, 48 },
                    { 542, "Thành phố Vũng Tàu", false, 49 },
                    { 543, "Thành phố Bà Rịa", false, 49 },
                    { 544, "Huyện Châu Đức", true, 49 },
                    { 545, "Huyện Xuyên Mộc", false, 49 },
                    { 546, "Huyện Long Điền", false, 49 },
                    { 547, "Huyện Đất Đỏ", false, 49 },
                    { 548, "Thị xã Phú Mỹ", false, 49 },
                    { 549, "Huyện Côn Đảo", false, 49 },
                    { 550, "Huyện 1", false, 50 },
                    { 551, "Huyện 12", false, 50 },
                    { 552, "Huyện Gò Vấp", false, 50 },
                    { 553, "Huyện Bình Thạnh", false, 50 },
                    { 554, "Huyện Tân Bình", false, 50 },
                    { 555, "Huyện Tân Phú", false, 50 },
                    { 556, "Huyện Phú NHuyện", false, 50 },
                    { 557, "Thành phố Thủ Đức", false, 50 },
                    { 558, "Huyện 3", false, 50 },
                    { 559, "Huyện 10", false, 50 },
                    { 560, "Huyện 11", false, 50 },
                    { 561, "Huyện 4", false, 50 },
                    { 562, "Huyện 5", false, 50 },
                    { 563, "Huyện 6", false, 50 },
                    { 564, "Huyện 8", false, 50 },
                    { 565, "Huyện Bình Tân", false, 50 },
                    { 566, "Huyện 7", false, 50 },
                    { 567, "Huyện Củ Chi", false, 50 },
                    { 568, "Huyện Hóc Môn", false, 50 },
                    { 569, "Huyện Bình Chánh", false, 50 },
                    { 570, "Huyện Nhà Bè", false, 50 },
                    { 571, "Huyện Cần Giờ", false, 50 },
                    { 572, "Thành phố Tân An", false, 51 },
                    { 573, "Thị xã Kiến Tường", false, 51 },
                    { 574, "Huyện Tân Hưng", false, 51 },
                    { 575, "Huyện Vĩnh Hưng", false, 51 },
                    { 576, "Huyện Mộc Hóa", false, 51 },
                    { 577, "Huyện Tân Thạnh", false, 51 },
                    { 578, "Huyện Thạnh Hóa", false, 51 },
                    { 579, "Huyện Đức Huệ", false, 51 },
                    { 580, "Huyện Đức Hòa", false, 51 },
                    { 581, "Huyện Bến Lức", false, 51 },
                    { 582, "Huyện Thủ Thừa", false, 51 },
                    { 583, "Huyện Tân Trụ", false, 51 },
                    { 584, "Huyện Cần Đước", false, 51 },
                    { 585, "Huyện Cần Giuộc", false, 51 },
                    { 586, "Huyện Châu Thành", false, 51 },
                    { 587, "Thành phố Mỹ Tho", false, 52 },
                    { 588, "Thị xã Gò Công", false, 52 },
                    { 589, "Thị xã Cai Lậy", false, 52 },
                    { 590, "Huyện Tân Phước", false, 52 },
                    { 591, "Huyện Cái Bè", false, 52 },
                    { 592, "Huyện Cai Lậy", false, 52 },
                    { 593, "Huyện Châu Thành", false, 52 },
                    { 594, "Huyện Chợ Gạo", false, 52 },
                    { 595, "Huyện Gò Công Tây", false, 52 },
                    { 596, "Huyện Gò Công Đông", false, 52 },
                    { 597, "Huyện Tân Phú Đông", true, 52 },
                    { 598, "Thành phố Bến Tre", false, 53 },
                    { 599, "Huyện Châu Thành", false, 53 },
                    { 600, "Huyện Chợ Lách", false, 53 },
                    { 601, "Huyện Mỏ Cày Nam", false, 53 },
                    { 602, "Huyện Giồng Trôm", false, 53 },
                    { 603, "Huyện Bình Đại", false, 53 },
                    { 604, "Huyện Ba Tri", true, 53 },
                    { 605, "Huyện Thạnh Phú", true, 53 },
                    { 606, "Huyện Mỏ Cày Bắc", false, 53 },
                    { 607, "Thành phố Trà Vinh", false, 54 },
                    { 608, "Huyện Càng Long", false, 54 },
                    { 609, "Huyện Cầu Kè", true, 54 },
                    { 610, "Huyện Tiểu Cần", true, 54 },
                    { 611, "Huyện Châu Thành", true, 54 },
                    { 612, "Huyện Cầu Ngang", true, 54 },
                    { 613, "Huyện Trà Cú", true, 54 },
                    { 614, "Huyện Duyên Hải", true, 54 },
                    { 615, "Thị xã Duyên Hải", false, 54 },
                    { 616, "Thành phố Vĩnh Long", false, 55 },
                    { 617, "Huyện Long Hồ", false, 55 },
                    { 618, "Huyện Mang Thít", false, 55 },
                    { 619, "Huyện Vũng Liêm", false, 55 },
                    { 620, "Huyện Tam Bình", false, 55 },
                    { 621, "Thị xã Bình Minh", false, 55 },
                    { 622, "Huyện Trà Ôn", false, 55 },
                    { 623, "Huyện Bình Tân", false, 55 },
                    { 624, "Thành phố Cao Lãnh", false, 56 },
                    { 625, "Thành phố Sa Đéc", false, 56 },
                    { 626, "Thành phố Hồng Ngự", true, 56 },
                    { 627, "Huyện Tân Hồng", false, 56 },
                    { 628, "Huyện Hồng Ngự", false, 56 },
                    { 629, "Huyện Tam Nông", false, 56 },
                    { 630, "Huyện Tháp Mười", false, 56 },
                    { 631, "Huyện Cao Lãnh", false, 56 },
                    { 632, "Huyện Thanh Bình", false, 56 },
                    { 633, "Huyện Lấp Vò", false, 56 },
                    { 634, "Huyện Lai Vung", false, 56 },
                    { 635, "Huyện Châu Thành", false, 56 },
                    { 636, "Thành phố Long Xuyên", false, 57 },
                    { 637, "Thành phố Châu Đốc", false, 57 },
                    { 638, "Huyện An Phú", true, 57 },
                    { 639, "Thị xã Tân Châu", false, 57 },
                    { 640, "Huyện Phú Tân", false, 57 },
                    { 641, "Huyện Châu Phú", false, 57 },
                    { 642, "Huyện Tịnh Biên", true, 57 },
                    { 643, "Huyện Tri Tôn", true, 57 },
                    { 644, "Huyện Châu Thành", false, 57 },
                    { 645, "Huyện Chợ Mới", false, 57 },
                    { 646, "Huyện Thoại Sơn", false, 57 },
                    { 647, "Thành phố Rạch Giá", false, 58 },
                    { 648, "Thành phố Hà Tiên", false, 58 },
                    { 649, "Huyện Kiên Lương", false, 58 },
                    { 650, "Huyện Hòn Đất", false, 58 },
                    { 651, "Huyện Tân Hiệp", false, 58 },
                    { 652, "Huyện Châu Thành", false, 58 },
                    { 653, "Huyện Giồng Riềng", true, 58 },
                    { 654, "Huyện Gò Quao", true, 58 },
                    { 655, "Huyện An Biên", false, 58 },
                    { 656, "Huyện An Minh", false, 58 },
                    { 657, "Huyện Vĩnh THuyện", true, 58 },
                    { 658, "Thành phố Phú Quốc", true, 58 },
                    { 659, "Huyện Kiên Hải", true, 58 },
                    { 660, "Huyện U Minh Thượng", true, 58 },
                    { 661, "Huyện Giang Thành", true, 58 },
                    { 662, "Huyện Ninh Kiều", false, 59 },
                    { 663, "Huyện Ô Môn", false, 59 },
                    { 664, "Huyện Bình Thuỷ", false, 59 },
                    { 665, "Huyện Cái Răng", false, 59 },
                    { 666, "Huyện Thốt Nốt", false, 59 },
                    { 667, "Huyện Vĩnh Thạnh", false, 59 },
                    { 668, "Huyện Cờ Đỏ", false, 59 },
                    { 669, "Huyện Phong Điền", false, 59 },
                    { 670, "Huyện Thới Lai", false, 59 },
                    { 671, "Thành phố Vị Thanh", false, 60 },
                    { 672, "Thành phố Ngã Bảy", false, 60 },
                    { 673, "Huyện Châu Thành A", false, 60 },
                    { 674, "Huyện Châu Thành", false, 60 },
                    { 675, "Huyện Phụng Hiệp", true, 60 },
                    { 676, "Huyện Vị Thuỷ", false, 60 },
                    { 677, "Huyện Long Mỹ", true, 60 },
                    { 678, "Thị xã Long Mỹ", false, 60 },
                    { 679, "Thành phố Sóc Trăng", true, 61 },
                    { 680, "Huyện Châu Thành", true, 61 },
                    { 681, "Huyện Kế Sách", true, 61 },
                    { 682, "Huyện Mỹ Tú", true, 61 },
                    { 683, "Huyện Cù Lao Dung", true, 61 },
                    { 684, "Huyện Long Phú", true, 61 },
                    { 685, "Huyện Mỹ Xuyên", true, 61 },
                    { 686, "Thị xã Ngã Năm", true, 61 },
                    { 687, "Huyện Thạnh Trị", true, 61 },
                    { 688, "Thị xã Vĩnh Châu", true, 61 },
                    { 689, "Huyện Trần Đề", true, 61 },
                    { 690, "Thành phố Bạc Liêu", false, 62 },
                    { 691, "Huyện Hồng Dân", false, 62 },
                    { 692, "Huyện Phước Long", true, 62 },
                    { 693, "Huyện Vĩnh Lợi", false, 62 },
                    { 694, "Thị xã Giá Rai", false, 62 },
                    { 695, "Huyện Đông Hải", false, 62 },
                    { 696, "Huyện Hoà Bình", false, 62 },
                    { 697, "Thành phố Cà Mau", false, 63 },
                    { 698, "Huyện U Minh", true, 63 },
                    { 699, "Huyện Thới Bình", true, 63 },
                    { 700, "Huyện Trần Văn Thời", true, 63 },
                    { 701, "Huyện Cái Nước", true, 63 },
                    { 702, "Huyện Đầm Dơi", true, 63 },
                    { 703, "Huyện Năm Căn", false, 63 },
                    { 704, "Huyện Phú Tân", false, 63 },
                    { 705, "Huyện Ngọc Hiển", false, 63 }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Email", "Password", "RoleId", "Username" },
                values: new object[,]
                {
                    { 1, "admin1.uit@gmail.com", "MTIzNDU2Nzg=", 1, "admin1" },
                    { 2, "admin2.uit@gmail.com", "MTIzNDU2Nzg=", 1, "admin2" },
                    { 3, "teacher1.uit@gmail.com", "MTIzNDU2Nzg=", 2, "teacher1" },
                    { 4, "teacher2.uit@gmail.com", "MTIzNDU2Nzg=", 2, "teacher2" },
                    { 5, "21520007@gm.uit.edu.vn", "MTIzNDU2Nzg=", 3, "SV21520007" },
                    { 6, "21520013@gm.uit.edu.vn", "MTIzNDU2Nzg=", 3, "SV21520013" },
                    { 7, "21520032@gm.uit.edu.vn", "MTIzNDU2Nzg=", 3, "SV21520032" },
                    { 8, "21520035@gm.uit.edu.vn", "MTIzNDU2Nzg=", 3, "SV21520035" }
                });

            migrationBuilder.InsertData(
                table: "Students",
                columns: new[] { "Id", "BranchId", "DateOfBirth", "DistrictId", "FullName", "Gender", "StudentSpecificId" },
                values: new object[,]
                {
                    { 1, 1, new DateTime(2003, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), 700, "Võ Thanh Bình", 0, "SV21520007" },
                    { 2, 1, new DateTime(2003, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), 693, "Trương Bá Cường", 0, "SV21520013" },
                    { 3, 2, new DateTime(2003, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), 567, "Đôn Khánh Duy", 0, "SV21520032" },
                    { 4, 7, new DateTime(2003, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), 252, "Nguyễn Hoàng Khánh Duy", 0, "SV21520035" },
                    { 5, 1, new DateTime(2003, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), 686, "Nguyễn Hữu Hiếu", 0, "SV21520053" },
                    { 6, 3, new DateTime(2003, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), 560, "Trần Hoàng Long", 0, "SV21520093" },
                    { 7, 5, new DateTime(2003, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), 420, "Trần Xuân Mạnh", 0, "SV21520099" },
                    { 8, 7, new DateTime(2003, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), 245, "Phạm Nhật Minh", 0, "SV21520102" },
                    { 9, 7, new DateTime(2003, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), 238, "Nguyễn Thị Phương", 1, "SV21520135" },
                    { 10, 5, new DateTime(2003, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), 385, "Huỳnh Bá Anh Quân", 0, "SV21520136" },
                    { 11, 6, new DateTime(2003, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), 301, "Vũ Quí San", 0, "SV21520143" },
                    { 12, 1, new DateTime(2003, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), 679, "Phan Huy Tiến", 0, "SV21520167" },
                    { 13, 1, new DateTime(2003, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), 672, "Nguyễn Thành Trung", 0, "SV21520179" },
                    { 14, 4, new DateTime(2003, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), 476, "Nguyễn Quang Trường", 0, "SV21520182" },
                    { 15, 5, new DateTime(2003, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), 392, "Bùi Thúy Vi", 1, "SV21520190" },
                    { 16, 1, new DateTime(2003, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), 665, "Nguyễn Minh Đức", 0, "SV21520210" },
                    { 17, 2, new DateTime(2003, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), 581, "Nguyễn Đình Tuấn Anh", 0, "SV21520251" },
                    { 18, 4, new DateTime(2003, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), 462, "Phù Hữu Đạt", 0, "SV21520262" },
                    { 19, 2, new DateTime(2003, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), 574, "Nguyễn Minh Đức", 0, "SV21520266" },
                    { 20, 7, new DateTime(2003, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), 231, "Hoàng Thị Ánh Dương", 1, "SV21520270" },
                    { 21, 6, new DateTime(2003, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), 294, "Nguyễn Lê Hoàng Hùng", 0, "SV21520285" },
                    { 22, 7, new DateTime(2003, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), 224, "Liêu Gia Khánh", 0, "SV21520291" },
                    { 23, 1, new DateTime(2003, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), 658, "Bế Hải Long", 0, "SV21520302" },
                    { 24, 1, new DateTime(2003, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), 651, "Phan Quốc An", 0, "SV21520438" },
                    { 25, 1, new DateTime(2003, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), 644, "Võ Minh Đông", 0, "SV21520608" },
                    { 26, 1, new DateTime(2003, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), 637, "Trương Hữu Minh Đức", 0, "SV21520626" },
                    { 27, 2, new DateTime(2003, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), 630, "Nguyễn Xuân Luân", 0, "SV21521066" },
                    { 28, 2, new DateTime(2003, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), 623, "Nguyễn Thị Khánh Ly", 1, "SV21521079" },
                    { 29, 2, new DateTime(2003, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), 616, "Đào Duy Từ", 0, "SV21521117" },
                    { 30, 2, new DateTime(2003, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), 609, "Nguyễn Hữu Trí", 0, "SV21521528" },
                    { 31, 2, new DateTime(2003, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), 602, "Nguyễn Xuân Tú", 0, "SV21521585" },
                    { 32, 2, new DateTime(2003, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), 595, "Nguyễn Thanh Tuấn", 0, "SV21521604" },
                    { 33, 2, new DateTime(2003, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), 588, "Lê Xuân Tùng", 0, "SV21521616" },
                    { 34, 3, new DateTime(2003, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), 553, "Lê Minh Thông", 0, "SV21521457" },
                    { 35, 3, new DateTime(2003, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), 546, "Nguyễn Thị Thúy", 1, "SV21521477" },
                    { 36, 3, new DateTime(2003, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), 539, "Nguyễn Thị Thủy Tiên", 1, "SV21520378" },
                    { 37, 3, new DateTime(2003, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), 532, "Trương Thảo Tiên", 1, "SV21521495" },
                    { 38, 3, new DateTime(2003, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), 525, "Trần Nguyễn Quang Trường", 0, "SV21521572" },
                    { 39, 3, new DateTime(2003, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), 518, "Đào Trung Nguyên", 1, "SV21521156" },
                    { 40, 3, new DateTime(2003, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), 511, "Dương Hoài Phong", 0, "SV21521236" },
                    { 41, 3, new DateTime(2003, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), 504, "Đặng Xuân Sang", 0, "SV21521332" },
                    { 42, 3, new DateTime(2003, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), 497, "Văn Duy Thanh", 1, "SV21521415" },
                    { 43, 4, new DateTime(2003, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), 490, "Trần Chí Thiện", 0, "SV21520365" },
                    { 44, 4, new DateTime(2003, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), 483, "Bùi Chí Trung", 0, "SV21521544" },
                    { 45, 4, new DateTime(2003, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), 469, "Huỳnh Ngọc Thiên Ân", 0, "SV21520423" },
                    { 46, 4, new DateTime(2003, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), 455, "Nguyễn Thị Thùy Dương", 1, "SV21520648" },
                    { 47, 4, new DateTime(2003, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), 448, "Nguyễn Hải Hưng", 0, "SV21520800" },
                    { 48, 4, new DateTime(2003, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), 441, "Nguyễn Thị Thu Huyền", 1, "SV21520863" },
                    { 49, 4, new DateTime(2003, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), 434, "Hồ Công Huynh", 0, "SV21520866" },
                    { 50, 4, new DateTime(2003, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), 427, "Phan Tấn Nhất Khâm", 0, "SV21520879" },
                    { 51, 5, new DateTime(2003, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), 413, "Phạm Hồ Anh Quân", 0, "SV21521286" },
                    { 52, 5, new DateTime(2003, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), 406, "Nguyễn Trần Thị Bích Trâm", 1, "SV21521520" },
                    { 53, 5, new DateTime(2003, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), 399, "Vòng Thủy Thùy Trang", 1, "SV21521525" },
                    { 54, 5, new DateTime(2003, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), 378, "Lê Nguyễn Công Toại", 0, "SV21520381" },
                    { 55, 5, new DateTime(2003, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), 371, "Trần Tiến Đạt", 0, "SV21520591" },
                    { 56, 5, new DateTime(2003, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), 364, "Nguyễn Thị Ngọc Diễm", 1, "SV21520597" },
                    { 57, 5, new DateTime(2003, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), 357, "Đào Quang Linh", 0, "SV21520984" },
                    { 58, 6, new DateTime(2003, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), 350, "Đinh Phạm Thiên Long", 0, "SV21521021" },
                    { 59, 6, new DateTime(2003, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), 343, "Nguyễn Tiến Luận", 0, "SV21521065" },
                    { 60, 6, new DateTime(2003, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), 336, "Nguyễn Thành Nhân", 0, "SV21521178" },
                    { 61, 6, new DateTime(2003, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), 329, "Phạm Tân Nhật", 0, "SV21521197" },
                    { 62, 6, new DateTime(2003, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), 322, "Trần Hoàng Thiên Phú", 0, "SV21521250" },
                    { 63, 6, new DateTime(2003, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), 315, "Phạm Công Thịnh", 0, "SV21521449" },
                    { 64, 6, new DateTime(2003, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), 308, "Trần Minh Tuấn", 0, "SV21521608" },
                    { 65, 6, new DateTime(2003, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), 287, "Nguyễn Thị Hà", 1, "SV21520691" },
                    { 66, 6, new DateTime(2003, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), 280, "Dương Lê Tường Khang", 0, "SV21520882" },
                    { 67, 7, new DateTime(2003, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), 273, "Phan Lê Phú", 0, "SV21521247" },
                    { 68, 7, new DateTime(2003, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), 266, "Nguyễn Hoàng Thắng", 0, "SV21521394" },
                    { 69, 7, new DateTime(2003, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), 259, "Huỳnh Minh Tuấn", 0, "SV21521596" },
                    { 70, 7, new DateTime(2003, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), 217, "Nguyễn Quốc Đạt", 0, "SV21520574" },
                    { 71, 7, new DateTime(2003, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), 210, "Nguyễn Thị Bích Diễm", 1, "SV21520596" },
                    { 72, 7, new DateTime(2003, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), 203, "Nguyễn Thị Thu Hiền", 1, "SV21520723" },
                    { 73, 8, new DateTime(2003, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), 196, "Nguyễn Minh Hiếu", 0, "SV21520747" },
                    { 74, 8, new DateTime(2003, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), 189, "Lê Quốc Huy", 0, "SV21520834" },
                    { 75, 8, new DateTime(2003, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), 182, "Nguyễn Thịnh Khang", 0, "SV21520894" },
                    { 76, 8, new DateTime(2003, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), 175, "Ngân Văn Luyện", 0, "SV21521074" },
                    { 77, 8, new DateTime(2003, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), 168, "Đinh Ngọc Phúc", 0, "SV21521251" },
                    { 78, 8, new DateTime(2003, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), 161, "Đoàn Minh Quang", 0, "SV21521292" },
                    { 79, 8, new DateTime(2003, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), 154, "Nguyễn Nhật Quang", 0, "SV21521300" },
                    { 80, 8, new DateTime(2003, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), 147, "Tống Đình Quốc", 0, "SV21521312" },
                    { 81, 8, new DateTime(2003, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), 140, "Trần Quốc Thắng", 0, "SV21521399" },
                    { 82, 8, new DateTime(2003, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), 133, "Nguyễn Hữu Tiến", 0, "SV21521487" },
                    { 83, 8, new DateTime(2003, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), 126, "Phạm Đức Toàn", 0, "SV21521511" },
                    { 84, 9, new DateTime(2003, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), 119, "Vũ Đức Tới", 0, "SV21521514" },
                    { 85, 9, new DateTime(2003, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), 112, "Mai Xuân Tú", 0, "SV21521581" },
                    { 86, 9, new DateTime(2003, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), 105, "Phạm Anh Tú", 0, "SV21521586" },
                    { 87, 9, new DateTime(2003, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), 98, "Đỗ Quốc Vinh", 0, "SV21521645" },
                    { 88, 9, new DateTime(2003, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), 91, "Trần Huy Thắng", 0, "SV21521695" },
                    { 89, 9, new DateTime(2003, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), 84, "Lê Phan Thành Đạt", 0, "SV21520570" },
                    { 90, 9, new DateTime(2003, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), 77, "Võ Thành Trung Dũng", 0, "SV21520641" },
                    { 91, 9, new DateTime(2003, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), 70, "Dương Thị Hồng Hạnh", 1, "SV21520711" },
                    { 92, 9, new DateTime(2003, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), 63, "Huỳnh Nhật Hào", 0, "SV21520714" },
                    { 93, 10, new DateTime(2003, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), 56, "Trần Trung Hiếu", 0, "SV21520754" },
                    { 94, 10, new DateTime(2003, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), 49, "Võ Trung Hiếu", 0, "SV21520758" },
                    { 95, 10, new DateTime(2003, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), 42, "Võ Kiều Hoa", 1, "SV21520767" },
                    { 96, 10, new DateTime(2003, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), 35, "Trần Nguyễn Anh Khoa", 0, "SV21520938" },
                    { 97, 10, new DateTime(2003, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), 28, "Nguyễn Thiên Long", 0, "SV21521046" },
                    { 98, 10, new DateTime(2003, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), 21, "Nguyễn Hoàng Nhân", 0, "SV21521176" },
                    { 99, 10, new DateTime(2003, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), 14, "Trịnh Ngọc Pháp", 0, "SV21521227" },
                    { 100, 10, new DateTime(2003, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), 7, "Nguyễn Thị Thắm", 1, "SV21521384" },
                    { 101, 10, new DateTime(2003, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), 443, "Nguyễn Quang Thuận", 0, "SV21521470" },
                    { 102, 10, new DateTime(2003, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), 668, "Nguyễn Thanh Tường Vi", 1, "SV21521636" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Branches_BranchName",
                table: "Branches",
                column: "BranchName",
                unique: true,
                filter: "[BranchName] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_Branches_BranchSpecificId",
                table: "Branches",
                column: "BranchSpecificId",
                unique: true,
                filter: "[BranchSpecificId] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_Branches_DepartmentId",
                table: "Branches",
                column: "DepartmentId");

            migrationBuilder.CreateIndex(
                name: "IX_Departments_DepartmentName",
                table: "Departments",
                column: "DepartmentName",
                unique: true,
                filter: "[DepartmentName] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_Departments_DepartmentSpecificId",
                table: "Departments",
                column: "DepartmentSpecificId",
                unique: true,
                filter: "[DepartmentSpecificId] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_Districts_DistrictName_ProvinceId",
                table: "Districts",
                columns: new[] { "DistrictName", "ProvinceId" },
                unique: true,
                filter: "[DistrictName] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_Districts_ProvinceId",
                table: "Districts",
                column: "ProvinceId");

            migrationBuilder.CreateIndex(
                name: "IX_PriorityTypes_PriorityName",
                table: "PriorityTypes",
                column: "PriorityName",
                unique: true,
                filter: "[PriorityName] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_Provinces_ProvinceName",
                table: "Provinces",
                column: "ProvinceName",
                unique: true,
                filter: "[ProvinceName] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_Roles_RoleName",
                table: "Roles",
                column: "RoleName",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_StudentPriorityTypes_PriorityTypeId",
                table: "StudentPriorityTypes",
                column: "PriorityTypeId");

            migrationBuilder.CreateIndex(
                name: "IX_Students_BranchId",
                table: "Students",
                column: "BranchId");

            migrationBuilder.CreateIndex(
                name: "IX_Students_DistrictId",
                table: "Students",
                column: "DistrictId");

            migrationBuilder.CreateIndex(
                name: "IX_Students_StudentSpecificId",
                table: "Students",
                column: "StudentSpecificId",
                unique: true,
                filter: "[StudentSpecificId] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_Users_Email",
                table: "Users",
                column: "Email",
                unique: true,
                filter: "[Email] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_Users_RoleId",
                table: "Users",
                column: "RoleId");

            migrationBuilder.CreateIndex(
                name: "IX_Users_Username",
                table: "Users",
                column: "Username",
                unique: true,
                filter: "[Username] IS NOT NULL");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "StudentPriorityTypes");

            migrationBuilder.DropTable(
                name: "Users");

            migrationBuilder.DropTable(
                name: "PriorityTypes");

            migrationBuilder.DropTable(
                name: "Students");

            migrationBuilder.DropTable(
                name: "Roles");

            migrationBuilder.DropTable(
                name: "Branches");

            migrationBuilder.DropTable(
                name: "Districts");

            migrationBuilder.DropTable(
                name: "Departments");

            migrationBuilder.DropTable(
                name: "Provinces");
        }
    }
}
